import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
   <div className='flex w-full h-screen m-3 p-4 justify-center '>
    <Head>
      <title>Wangila dev forlio </title>
      <meta name='description' content='generated by Wangila'></meta>
    </Head>
      <main>
        <h1>Emmanuel Wangila</h1>
      </main>
   </div>
  )
}
